# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "almalinux/9"
  config.vm.hostname = "chat"

  # Provision with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/chat.yml"
    #Will use later, have not needed this yet
    #ansible.inventory_path = "../ansible/inventory.yml"
    ansible.limit = "all"
    ansible.verbose = "vv"
  end
end

